dist: xenial
language: python
python:
- '3.6'
sudo: required
branches:
  only:
  - source
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
    secure: q2mD16jPP5LfjKhl2x2NR+NCq6GGjM8gveT3Xy6GtA19oFdXP2/6cnW571PBb/tNPCe1tSADRBTYnRXt9sbmy0VWV7+ddZ9EsjuNgTzVfVO2K+OglBOh3nyT+6gFaLws1EUafVyoRRE0rsBEucwyhRzQGXGqzIyRctgYtF3CXqMLVR2liXuD7rK2t4W2HXX+aYOd/J3cT7PAmVi39hwCciJfG2l2NIjDYj2/tZI9CsU1174BQbl7ck0q60S6kFc/v2srq1CMLpJ5CffDoJmMfPURQk8KmDe7D2DBtEd2KC8ZZ0Z86HbRycttobqauZT820d0GLjAPD8T9H7IvDPwJxMpkEoIyaS7yTl7DW9fKo0P4AsOjAtU9WztTSsAomcddPERYquOObQR1OL4I9G0cj+DVbv8/LUSt+AzEOU6IRdrtWrKNXAizf8wrO/V6y/uJotOdBPOb5LlO+p0qFyM+MgLOCWUtt8KvbCiKI5fZI2aHt8SwOzTYsqqJEV47bDb2JgPKLNqqTWNDLzTxK78OBgEY+fSTyjkbOg2NNpCp9CPflQYyqdbynr1YvTPAU5JxZj/KwgjCMsUeeHNQvL2m3NizVQL+zdJGYzqnGSpP6W6dT/b2oWDPPsNw+/3RM3vRJ5lPuQzuZQVHkh1zrJW0DWgadVsJeXBl9P8udI1LEQ=
