dist: xenial
language: python
python:
- '3.7'
sudo: required
branches:
  only:
  - source
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
  - secure: c+9qzDYu6QHGz2eWIjKUSh3nnnWsdf/jAFeYayZS9VL2TxIh0qdv7PTnJpUYc6KCzvunYO00h3bVsXoG7uSa/18i6xPAM5aAN8yD3Hoo1TUxZOCCkk+0IqWs+oKN4Ql8nx2HVKn8RsMvv//LUIeIGFQ8fDbOFZqsEX/stpoBvHJjfID0Rg6E+h6R72QFh61KcozihqNiy1a3o4s45Foz2vwEqxARpunejzrmDAahPGojMikdtV2/dqWSPh0r4Ji27nW+reA5WjT1VFGlRK2YCPoXBZrJIsNg1sRqZzInJGc+cTlLlaP4VST9E5qdA++gtz8XAj3KxrlHqH22dCAmiyppKQCPJg5YlAky3dQRGTdMGXB33rhSbsNxkdO/7MkWUbIBQUk6z+kgESKhFmMeoKpwK/6a5cBylIgM18XM/FKNAY7Uinyo9RlsH3H+faaC2prUpBL8WpJKtEvlAjSOlrd4cV3P93qPa3kEm4JitkKnQFdU5lHQ/oLxp9P57oItJNWBoCzPDbX0RoHelTqKRm5LR4gUQT8y9kel3A5ySASuqj8fkwdsasSu6zGQJaJ3pzw7LP3vuwJpYg14qmFi2oCN5SVGLYsPWEdXFxETEyiSZa/VW/m/ZTRvrhgt2sygvfex0GuKXvL9rGoF/rG6O8xeg76mBSw1iOxBhateuxo=
